ab_transcoding_experiments_homepage:
    pattern:  /{filename}
    defaults: { _controller: ABTranscodingExperimentsBundle:Default:index, filename: bbb30.mp4 }

ab_transcoding_experiments_serve_payload:
    pattern:  /servePayload/{lengthKB}/{startTime}
    defaults: { _controller: ABTranscodingExperimentsBundle:Default:servePayload, lengthKB: 500, startTime: 0 }

ab_transcoding_experiments_transcode:
    pattern:  /transcode/{clientBitrate}/{inputFilepath}/{startSecond}/stream.{containerFormat}
    defaults: { _controller: ABTranscodingExperimentsBundle:Default:transcode }
