imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    channels:   ["transcode", "transcode_send_data", "transcode_range_request"]
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
        transcode:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.transcode.log"
            level:  debug
            channels: transcode
        transcode_range_request:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.transcode_range_request.log"
            level:  debug
            channels: transcode_range_request
        transcode_send_data:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.transcode_send_data.log"
            level:  info
            channels: transcode_send_data
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        firephp:
            type:   firephp
            level:  info
        #chromephp:
         #   type:   chromephp
         #   level:  debug

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com
